apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: {{ template "azure-cosmosdb-mongo.fullname" . }}
  labels:
    app: {{ template "azure-cosmosdb-mongo.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  instanceRef:
    name: {{ template "azure-cosmosdb-mongo.fullname" . }}
  secretName: {{ template "azure-cosmosdb-mongo.fullname" . }}