apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "azure-capture-order.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "azure-capture-order.fullname" . }}
spec:
  clusterIP: "{{ .Values.service.clusterIP }}"
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
{{- if and (ge .Capabilities.KubeVersion.Minor "7") (.Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
{{- end }}
  ports:
    - name: http
      port: {{ .Values.service.externalPort }}
      protocol: TCP
      targetPort: 8080
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ template "azure-capture-order.name" . }}
    component: "{{ .Values.name }}"
    release: {{ .Release.Name }}
  type: "{{ .Values.service.type }}"